---
title: "Results Weighted"
author: "Maksim Zubok"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output: 
  pdf_document:
    latex_engine: lualatex
    toc: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      results='asis')


pacman::p_load(rio, tidyverse, readr, broom, 
               lubridate, gt, gtsummary, survey, readxl,
               gridExtra, knitr, haven, stargazer, nnet)

DATA_CODES = "https://cdn.githubraw.com/antndlcrx/nonviolent-repression/main/data/acled_raw_data/region_codes.xlsx"

acled <- import("C:/Users/murrn/GitHub/nonviolent-repression/data/acled_processed_data/acled_with_org_indicator.csv") 

codes = data <- openxlsx::read.xlsx(DATA_CODES, sheet = "Sheet1")
codes <- codes %>%
  mutate(region_name_en = str_trim(region_name_en))


## unique observations 

length(unique(acled$notes))
# Finding duplicate observations in 'variable'
duplicates <- duplicated(acled$notes)

# Getting the row IDs of these duplicates
row_ids <- which(duplicates)

# Print events
acled$notes[row_ids]
acled_clean <- acled[!duplicated(acled$notes), ]

acled_clean <- acled_clean %>% 
  mutate(
    date = ymd(as.character(event_date)),
    month_year = as.Date(paste0(month_year, "-01"))
    )

# Convert date column to Date object and create DVs:
# pre/post invasion
# election_month
acled_clean <- acled_clean %>% 
  mutate(date = ymd(event_date),
         pred_labels = recode(pred_labels,
                              "war (pro)" = "war_pro",
                              "war (anti)" = "war_anti"),
         month_year = format(date, "%Y-%m"),
         post_invasion = case_when(
    date >= as.Date("2022-02-24") ~ 1,
    TRUE ~ 0),
    police_violence = case_when(
    sub_event_type %in% c("Protest with intervention", "Excessive force against protesters") ~ 1,
    TRUE ~ 0
  ),
    election_month = case_when(
           month_year %in% c("2021-09", "2018-03", "2024-03", "2020-06", "2020-07") ~ 1,
           TRUE ~ 0)
    )


mapping <- c(
  'Saint Petersburg' = 'The City of Saint-Petersburg',
  'Sverdlovsk' = 'Sverdlovsk region',
  'Moscow' = 'The City of Moscow',
  'Republic of Tatarstan' = 'Republic of Tatarstan',
  'Novosibirsk' = 'Novosibirsk region',
  'Novgorod' = 'Novgorod region',
  'Samara' = 'Samara region',
  'Republic of Mari El' = 'Republic of Mariy El',
  'Republic of Dagestan' = 'Republic of Daghestan',
  'Tomsk' = 'Tomsk region',
  'Republic of Karachay-Cherkessia' = 'Karachaev-Circassian Republic',
  'Moscow Oblast' = 'Moscow region',
  'Volgograd' = 'Volgograd region',
  'Chelyabinsk' = 'Chelyabinsk region',
  'Kaliningrad' = 'Kaliningrad region',
  'Khabarovsk' = 'Khabarovsk territory',
  'Republic of Khakassia' = 'Republic of Khakassia',
  'Perm' = 'Perm region',
  'Vologda' = 'Vologda region',
  'Republic of Sakha' = 'Republic of Sakha (Yakutia)',
  'Tula' = 'Tula region',
  'Kemerovo' = 'Kemerovo region',
  'Altai' = 'Altai territory',
  'Republic of Bashkortostan' = 'Republic of Bashkortastan',
  'Penza' = 'Penza region',
  'Republic of Chuvash' = 'Chuvash Republic',
  'Krasnoyarsk' = 'Krasnoyarsk territory',
  'Orenburg' = 'Orenburg region',
  'Tyumen' = 'Tyumen region',
  'Republic of Kabardino-Balkaria' = 'Kabardian-Balkar Republic',
  'Kostroma' = 'Kostroma region',
  'Vladimir' = 'Vladimir region',
  'Arkhangelsk' = 'Arkhangelsk region',
  'Rostov' = 'Rostov region',
  'Krasnodar' = 'Krasnodar territory',
  'Khanty-Mansi' = 'Khanty-Mansi autonomous',
  'Kaluga' = 'Kaluga region',
  'Republic of Karelia' = 'Republic of Karelia',
  'Voronezh' = 'Voronezh region',
  'Ryazan' = 'Ryazan region',
  'Zabaykalskiy' = 'Chita region',
  'Ulyanovsk' = 'Ulyanovsk region',
  'Republic of Komi' = 'Republic of Komi',
  'Republic of Buryatia' = 'Republic of Buryatia',
  'Nizhny Novgorod' = 'Nizhny novgorod region',
  'Ivanovo' = 'Ivanovo region',
  'Saratov' = 'Saratov region',
  'Irkutsk' = 'Irkutsk region',
  'Republic of Altai' = 'Republic of Altai',
  'Primorskiy' = 'Primorsky territory',
  'Republic of Chechnya' = 'Chechen Republic',
  'Belgorod' = 'Belgorod region',
  'Lipetsk' = 'Lipetsk region',
  'Udmurt Republic' = 'Udmurt Republic',
  'Astrakhan' = 'Astrakhan region',
  'Kirov' = 'Kirov region',
  'Yaroslavl' = 'Yaroslavl region',
  'Kursk' = 'Kursk region',
  'Omsk' = 'Omsk region',
  'Republic of Mordovia' = 'Republic of Mordovia',
  'Tambov' = 'Tambov region',
  'Smolensk' = 'Smolensk region',
  'Republic of Ingushetia' = 'Republic of Ingushetia',
  'Oryol' = 'Oryol region',
  'Pskov' = 'Pskov region',
  'Republic of Tuva' = 'Republic of Tyva',
  'Republic of North Ossetia-Alania' = 'Republic of North Ossetia -Alania',
  'Jewish Autonomous Oblast' = 'Jewish autonomous region',
  'Kamchatka' = 'Kamchatka region',
  'Magadan' = 'Magadan region',
  'Republic of Kalmykia' = 'Republic of Kalmykia',
  'Yamalo-Nenets' = 'Yamalo-Nenets autonomous',
  'Bryansk' = 'Bryansk region',
  'Stavropol' = 'Stavropol territory',
  'Tver' = 'Tver region',
  'Murmansk' = 'Murmansk region',
  'Republic of Adygea' = 'Republic of Adygeya',
  'Amur' = 'Amur region',
  'Sakhalin' = 'Sakhalin region',
  'Leningrad' = 'Leningrad region',
  'Chukotka' = 'Chukotka autonomous area',
  'Nenets' = 'Nenets autonomous area',
  'Kurgan' = 'Kurgan region'
)


# apply mapping
acled_clean$admin1 <- mapping[acled_clean$admin1]

# create dummies for protest types
acled_clean_dummy <- acled_clean %>%
  mutate(pred_labels = factor(pred_labels)) %>%
  mutate(dummy = 1) %>%
  pivot_wider(names_from = pred_labels, values_from = dummy, values_fill = list(dummy = 0)) %>% 
  mutate(non_pol = case_when(political == 1 ~ 0,
                             TRUE ~ 1))

```



```{r}
# pol_base <- lm(political ~ post_invasion, acled_clean_dummy)
pol_base <- glm(political ~ post_invasion  + month_year, data = acled_clean_dummy, family = binomial)
nonpol_base <- glm(non_pol ~ post_invasion + month_year, data = acled_clean_dummy, family = binomial)

pol_controls <- glm(political ~ post_invasion + election_month + month_year + admin1, data = acled_clean_dummy, family = binomial)
nonpol_controls <- glm(non_pol ~ post_invasion + election_month + month_year + admin1, data = acled_clean_dummy, family = binomial)

# summary(pol_base)
```

```{r}
acled_clean_dummy_no_war <- acled_clean_dummy %>% 
  mutate() %>% 
  filter(!(war_pro == 1 | war_anti == 1))

# nonpol_subset_nowar <- lm(non_pol ~ post_invasion, acled_clean_dummy_no_war)
nonpol_nowar <- glm(non_pol ~ post_invasion + month_year, data = acled_clean_dummy_no_war, family = binomial)
nonpol_nowar_controls <- glm(non_pol ~ post_invasion + election_month + month_year + admin1, data = acled_clean_dummy_no_war, family = binomial)

# summary(nonpol_subset_nowar)

```


```{r}
models = list(pol_base, pol_controls, 
          nonpol_base, nonpol_controls, nonpol_nowar,
          nonpol_nowar_controls)

stargazer(models,
          digits=2,
          header=FALSE,
          no.space = TRUE, # to remove the spaces after each 
          column.sep.width = "2pt", # to reduce column width
          font.size = "small", # to make font size smaller
          dep.var.labels=c("Political Protest", "Other Protest"),
          covariate.labels=c("Post Invasion", "Election Month"),

          title="Log Odds of Protest",
          notes = '',
  notes.append = TRUE,
  notes.align = 'l',
  omit = c("month", "year", "admin"),
  add.lines = list(c('Month-Year FE','Yes','Yes','Yes', 'Yes', 'Yes', 'Yes'),
                   c('War Protests Excluded', 'No', 'No', 'No', 'No', 'Yes', 'Yes'),
                   c('Region FE', 'No', "Yes", "No", "Yes", "No", "Yes")
                   )
          )
```


```{r echo = FALSE, warning = FALSE, message = FALSE, results=FALSE}
m_log <- multinom(org_indicator ~ post_invasion + month_year, data = acled_clean_dummy)

m_log_controls <- multinom(org_indicator ~  post_invasion + election_month + month_year + admin1, data = acled_clean_dummy)
```


```{r}
stargazer(m_log, m_log_controls,
          digits=2,
          header=FALSE,
          no.space = TRUE, # to remove the spaces after each 
          column.sep.width = "2pt", # to reduce column width
          font.size = "small", # to make font size smaller
          dep.var.labels=c("Other", "Pro Kremlin", "Systemic Opposition", "Other", "Pro Kremlin", "Systemic Opposition"),
          covariate.labels=c("Post Invasion", "Election Month"),

          title="Log Odds of Protest by Protest Organiser",
          notes = '',
  notes.append = TRUE,
  notes.align = 'l',
  omit = c("month", "year", "admin"),
  add.lines = list(c('Month-Year FE','Yes','Yes', 'Yes','Yes','Yes','Yes'),
                   c('War Protests Excluded', 'No', 'No','No', 'No','No', 'No'),
                   c('Region FE', 'No','No', 'No', "Yes", 'Yes','Yes')
                   )
          )

```

